// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9OsKq4fsecQ3Shx-3KdYObfY3rzTOHc',
    appId: '1:362133696016:web:a979321966856af7652495',
    messagingSenderId: '362133696016',
    projectId: 'rakan-firebase',
    authDomain: 'rakan-firebase.firebaseapp.com',
    databaseURL: 'https://rakan-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rakan-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKVtRieYPwxKmjd-dKrlt4V5ZMQ82jEmI',
    appId: '1:362133696016:android:c4f307255df1c5d1652495',
    messagingSenderId: '362133696016',
    projectId: 'rakan-firebase',
    databaseURL: 'https://rakan-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rakan-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp1X1oafurX5jpe0uFlKeKrl-3eEHntVg',
    appId: '1:362133696016:ios:45aa8bbaff69be25652495',
    messagingSenderId: '362133696016',
    projectId: 'rakan-firebase',
    databaseURL: 'https://rakan-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rakan-firebase.appspot.com',
    iosClientId: '362133696016-aprk835jbclrus2jj2sg5l6go8nkq5qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp1X1oafurX5jpe0uFlKeKrl-3eEHntVg',
    appId: '1:362133696016:ios:45aa8bbaff69be25652495',
    messagingSenderId: '362133696016',
    projectId: 'rakan-firebase',
    databaseURL: 'https://rakan-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rakan-firebase.appspot.com',
    iosClientId: '362133696016-aprk835jbclrus2jj2sg5l6go8nkq5qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
